runtime: python312  # Adjust based on your Python version (python39 for Python 3.9)

entrypoint: gunicorn -b :$PORT csc4130WebServer.wsgi  # This is the entrypoint for your Django project

#instance_class: F2 Optional, choose instance class based on your app's requirements
#automatic_scaling:
# target_cpu_utilization: 0.65
 # max_instances: 2

env_variables:
  DJANGO_SETTINGS_MODULE: "csc4130WebServer.settings"
  # Add other environment variables if necessary
  APPENGINE_URL: https://PROJECT_ID.uc.r.appspot.com
  SECRET_KEY: "django-insecure-lg3c(!hwf4mw2mk8t-yf!=#l5)!6$#m090l^mm&#+x0ey3=he-"  # Replace with your Django secret key

handlers:
  - url: /static
    static_dir: static  # Serve static files (run `collectstatic` in Django to collect these files)

  - url: /.*
    script: auto  # Direct everything else to Django's WSGI app
# 