# Generated by Django 4.2.2 on 2024-08-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_sensordata_date_remove_sensordata_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='humidity',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
