# Generated by Django 4.2.2 on 2024-09-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sensordata_humidity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='humidity',
            field=models.FloatField(default=0.0),
        ),
    ]
